textures = {
    '_default_fence_acacia_wood': ('acacia_wood', 'fence', 'fence'),
    '_default_fence_acacia_wood_sides': ('acacia_wood', 'fence_sides', 'fence_sides'),
    '_default_fence_acacia_wood_topbottom': ('acacia_wood', 'fence_topbottom', 'fence_topbottom'),
    '_default_fence_aspen_wood': ('aspen_wood', 'fence', 'fence'),
    '_default_fence_aspen_wood_sides': ('aspen_wood', 'fence_sides', 'fence_sides'),
    '_default_fence_aspen_wood_topbottom': ('aspen_wood', 'fence_topbottom', 'fence_topbottom'),
    '_default_fence_junglewood': ('jungle_wood', 'fence', 'fence'),
    '_default_fence_junglewood_sides': ('jungle_wood', 'fence_sides', 'fence_sides'),
    '_default_fence_junglewood_topbottom': ('jungle_wood', 'fence_topbottom', 'fence_topbottom'),
    '_default_fence_pine_wood': ('pine_wood', 'fence', 'fence'),
    '_default_fence_pine_wood_sides': ('pine_wood', 'fence_sides', 'fence_sides'),
    '_default_fence_pine_wood_topbottom': ('pine_wood', 'fence_topbottom', 'fence_topbottom'),
    '_default_fence_wood': ('wood', 'fence', 'fence'),
    '_default_fence_wood_sides': ('wood', 'fence_sides', 'fence_sides'),
    '_default_fence_wood_topbottom': ('wood', 'fence_topbottom', 'fence_topbottom'),
    'default_acacia_leaves': (('acacia_leaves_1', 'acacia_leaves_2'), 'acacia_leaves', 'leaves'),
    'default_acacia_sapling': (('acacia_tree', 'acacia_leaves_1'), 'sapling', 'sapling'),
    'default_acacia_tree': ('acacia_tree', 'tree'),
    'default_acacia_tree_top': (('acacia_tree', 'acacia_wood'), 'tree_top'),
    'default_acacia_wood': ('acacia_wood', 'wood'),
    'default_apple': (('apple', 'grass'), 'apple', 'apple'),
    'default_aspen_leaves': ('aspen_leaves', 'simple_block', 'leaves'),
    'default_aspen_sapling': (('aspen_tree', 'aspen_leaves'), 'sapling', 'sapling'),
    'default_aspen_tree': ('aspen_tree', 'aspen_tree'),
    'default_aspen_tree_top': (('aspen_tree', 'aspen_wood'), 'aspen_tree_top'),
    'default_aspen_wood': ('aspen_wood', 'wood'),
    'default_book': (('book', 'paper'), 'book', 'book'),
    'default_book_written': (('book', 'paper', 'color_black'), 'book_written', 'book'),
    'default_bookshelf': (('wood', 'color_light_lime', 'color_light_cyan', 'color_light_red', 'color_light_aqua', 'color_light_violet', 'color_light_skyblue', 'color_light_yellow', 'color_light_blue', 'color_light_green', 'color_light_orange'), 'bookshelf'),
    'default_brick': ('clay_brick', 'brick'),
    'default_bronze_block': ('bronze', 'ore_block'),
    'default_bronze_ingot': ('bronze', 'cuboid', 'cuboid'),
    'default_cactus_side': (('cactus_1', 'cactus_2'), 'cactus_side'),
    'default_cactus_top': (('cactus_1', 'cactus_2'), 'cactus_top'),
    'default_chest_front': (('wood', 'steel'), 'chest_front'),
    'default_chest_lock': (('wood', 'steel'), 'chest_lock'),
    'default_chest_side': ('wood', 'chest_side'),
    'default_chest_top': ('wood', 'chest_top'),
    'default_clay': ('clay', 'sand'),
    'default_clay_brick': ('clay_brick', 'cuboid', 'cuboid'),
    'default_clay_lump': ('clay', 'circle', 'circle'),
    'default_cloud': ('color_white', 'simple_block'),
    'default_coal_block': ('coal', 'ore_block'),
    'default_coal_lump': ('coal', 'ore_lump', 'ore_lump'),
    'default_cobble': ('stone', 'cobble'),
    'default_copper_block': ('copper', 'ore_block'),
    'default_copper_ingot': ('copper', 'cuboid', 'cuboid'),
    'default_copper_lump': ('copper', 'ore_lump', 'ore_lump'),
    'default_desert_cobble': ('desert_stone', 'cobble'),
    'default_desert_sand': ('desert_sand', 'sand'),
    'default_desert_stone': ('desert_stone', 'simple_block'),
    'default_desert_stone_block': ('desert_stone', 'ore_block'),
    'default_desert_stone_brick': ('desert_stone', 'brick'),
    'default_diamond': ('diamond', 'ore_crystal', 'ore_crystal'),
    'default_diamond_block': ('diamond', 'ore_block'),
    'default_dirt': ('dirt', 'simple_block'),
    'default_dry_grass': ('dry_grass', 'simple_block'),
    'default_dry_grass_1': ('dry_grass', 'simple_block_dark', 'grass_1'),
    'default_dry_grass_2': ('dry_grass', 'simple_block_dark', 'grass_2'),
    'default_dry_grass_3': ('dry_grass', 'simple_block_dark', 'grass_3'),
    'default_dry_grass_4': ('dry_grass', 'simple_block_dark', 'grass_4'),
    'default_dry_grass_5': ('dry_grass', 'simple_block_dark', 'grass_5'),
    'default_dry_grass_side': ('dry_grass', 'simple_block', 'grass_side'),
    'default_dry_shrub': ('dry_shrub', 'simple_block', 'grass_3'),
    'default_flint': ('stone', 'circle', 'circle'),
    'default_furnace_bottom': 'default_furnace_top',
    'default_furnace_fire_bg': ('color_gray', 'simple_block', 'furnace_fire'),
    'default_furnace_fire_fg': ('fire', 'simple_block', 'furnace_fire'),
    'default_furnace_front': (('stone', 'color_black', 'color_black'), 'furnace_front'),
    'default_furnace_front_active': (('stone', 'fire', 'color_black'), 'furnace_front'),
    'default_furnace_side': ('stone', 'furnace_side'),
    'default_furnace_top': ('stone', 'furnace_top'),
    'default_glass': ('glass', 'simple_block', 'glass'),
    'default_glass_detail': ('glass', 'simple_block', 'glass_detail'),
    'default_gold_block': ('gold', 'ore_block'),
    'default_gold_ingot': ('gold', 'cuboid', 'cuboid'),
    'default_gold_lump': ('gold', 'ore_lump', 'ore_lump'),
    'default_grass': ('grass', 'simple_block'),
    'default_grass_1': ('grass', 'simple_block_dark', 'grass_1'),
    'default_grass_2': ('grass', 'simple_block_dark', 'grass_2'),
    'default_grass_3': ('grass', 'simple_block_dark', 'grass_3'),
    'default_grass_4': ('grass', 'simple_block_dark', 'grass_4'),
    'default_grass_5': ('grass', 'simple_block_dark', 'grass_5'),
    'default_grass_side': ('grass', 'simple_block', 'grass_side'),
    'default_gravel': ('stone', 'sand'),
    'default_ice': ('ice', 'simple_block'),
    'default_iron_lump': ('iron_ore', 'ore_lump', 'ore_lump'),
    'default_junglegrass': ('jungle_grass', 'simple_block_dark', 'grass_5'),
    'default_jungleleaves': ('jungle_leaves', 'simple_block', 'leaves'),
    'default_jungleleaves_simple': 'default_jungleleaves',
    'default_junglesapling': (('jungle_tree', 'jungle_leaves'), 'sapling', 'sapling'),
    'default_jungletree': ('jungle_tree', 'tree'),
    'default_jungletree_top': (('jungle_tree', 'jungle_wood'), 'tree_top'),
    'default_junglewood': ('jungle_wood', 'wood'),
    'default_ladder_steel': ('steel', 'ladder', 'ladder'),
    'default_ladder_wood': ('wood', 'ladder', 'ladder'),
    'default_lava': ('lava', 'simple_block'),
    'default_lava_flowing_animated': 'default_lava',
    'default_lava_source_animated': 'default_lava',
    'default_leaves': ('leaves', 'simple_block', 'leaves'),
    'default_leaves_simple': 'default_leaves',
    'default_mese_block': ('mese', 'ore_block'),
    'default_mese_crystal': ('mese', 'ore_crystal', 'ore_crystal'),
    'default_mese_crystal_fragment': ('mese', 'fragment', 'fragment'),
    'default_meselamp': (('mese', 'glass'), 'mese_lamp'),
    'default_mineral_coal': ('coal', 'simple_block', 'mineral'),
    'default_mineral_copper': ('copper', 'simple_block', 'mineral'),
    'default_mineral_diamond': ('diamond', 'simple_block', 'mineral'),
    'default_mineral_gold': ('gold', 'simple_block', 'mineral'),
    'default_mineral_iron': ('iron_ore', 'simple_block', 'mineral'),
    'default_mineral_mese': ('mese', 'simple_block', 'mineral'),
    'default_mossycobble': ('mossy_stone', 'cobble'),
    'default_obsidian': ('obsidian', 'simple_block'),
    'default_obsidian_block': ('obsidian', 'ore_block'),
    'default_obsidian_brick': ('obsidian', 'brick'),
    'default_obsidian_glass': ('obsidian', 'simple_block', 'glass'),
    'default_obsidian_glass_detail': ('obsidian', 'simple_block', 'glass_detail'),
    'default_obsidian_shard': ('obsidian', 'fragment', 'fragment'),
    'default_paper': ('paper', 'rectangle', 'rectangle'),
    'default_papyrus': ('papyrus', 'simple_block', 'papyrus'),
    'default_pine_needles': ('pine_leaves', 'simple_block', 'pine_needles'),
    'default_pine_sapling': (('pine_tree', 'pine_leaves'), 'sapling', 'sapling'),
    'default_pine_tree': ('pine_tree', 'tree'),
    'default_pine_tree_top': (('pine_tree', 'pine_wood'), 'tree_top'),
    'default_pine_wood': ('pine_wood', 'wood'),
    'default_river_water': ('river_water', 'simple_block'),
    'default_river_water_flowing_animated': 'default_river_water',
    'default_river_water_source_animated': 'default_river_water',
    'default_sand': ('sand', 'sand'),
    'default_sandstone': ('sandstone', 'simple_block'),
    'default_sandstone_block': ('sandstone', 'ore_block'),
    'default_sandstone_brick': ('sandstone', 'brick'),
    'default_sapling': (('tree', 'leaves'), 'sapling', 'sapling'),
    'default_sign_steel': ('steel', 'sign', 'sign'),
    'default_sign_wall_steel': ('steel', 'sign_wall', 'sign_wall'),
    'default_sign_wall_wood': ('wood', 'sign_wall', 'sign_wall'),
    'default_sign_wood': ('wood', 'sign', 'sign'),
    'default_silver_sand': ('silver_sand', 'sand'),
    'default_snow': ('snow', 'simple_block'),
    'default_snow_side': ('snow', 'simple_block', 'grass_side'),
    'default_snowball': ('snow', 'circle', 'circle'),
    'default_steel_block': ('steel', 'ore_block'),
    'default_steel_ingot': ('steel', 'cuboid', 'cuboid'),
    'default_stick': ('wood', 'simple_block', 'stick'),
    'default_stone': ('stone', 'simple_block'),
    'default_stone_block': ('stone', 'ore_block'),
    'default_stone_brick': ('stone', 'brick'),
    'default_tool_bronzeaxe': (('bronze', 'wood'), 'axe', 'axe'),
    'default_tool_bronzepick': (('bronze', 'wood'), 'pick', 'pick'),
    'default_tool_bronzeshovel': (('bronze', 'wood'), 'shovel', 'shovel'),
    'default_tool_bronzesword': (('bronze', 'wood'), 'sword', 'sword'),
    'default_tool_diamondaxe': (('diamond', 'wood'), 'axe', 'axe'),
    'default_tool_diamondpick': (('diamond', 'wood'), 'pick', 'pick'),
    'default_tool_diamondshovel': (('diamond', 'wood'), 'shovel', 'shovel'),
    'default_tool_diamondsword': (('diamond', 'wood'), 'sword', 'sword'),
    'default_tool_meseaxe': (('mese', 'wood'), 'axe', 'axe'),
    'default_tool_mesepick': (('mese', 'wood'), 'pick', 'pick'),
    'default_tool_meseshovel': (('mese', 'wood'), 'shovel', 'shovel'),
    'default_tool_mesesword': (('mese', 'wood'), 'sword', 'sword'),
    'default_tool_steelaxe': (('steel', 'wood'), 'axe', 'axe'),
    'default_tool_steelpick': (('steel', 'wood'), 'pick', 'pick'),
    'default_tool_steelshovel': (('steel', 'wood'), 'shovel', 'shovel'),
    'default_tool_steelsword': (('steel', 'wood'), 'sword', 'sword'),
    'default_tool_stoneaxe': (('stone', 'wood'), 'axe', 'axe'),
    'default_tool_stonepick': (('stone', 'wood'), 'pick', 'pick'),
    'default_tool_stoneshovel': (('stone', 'wood'), 'shovel', 'shovel'),
    'default_tool_stonesword': (('stone', 'wood'), 'sword', 'sword'),
    'default_tool_woodaxe': (('wood', 'wood'), 'axe', 'axe'),
    'default_tool_woodpick': (('wood', 'wood'), 'pick', 'pick'),
    'default_tool_woodshovel': (('wood', 'wood'), 'shovel', 'shovel'),
    'default_tool_woodsword': (('wood', 'wood'), 'sword', 'sword'),
    'default_torch_on_floor': (('wood', 'fire'), 'torch_floor', 'torch_floor'),
    'default_torch_on_floor_animated': 'default_torch_on_floor',
    'default_tree': ('tree', 'tree'),
    'default_tree_top': (('tree', 'wood'), 'tree_top'),
    'default_water': ('water', 'simple_block'),
    'default_water_flowing_animated': 'default_water',
    'default_water_source_animated': 'default_water',
    'default_wood': ('wood', 'wood'),
    'gui_formbg': ('color_dark_gray', 'simple_block'),
    'gui_furnace_arrow_bg': ('color_gray', 'simple_block', 'arrow_up'),
    'gui_furnace_arrow_fg': ('color_cyan', 'simple_block', 'arrow_up'),
    'gui_hb_bg': ('color_black', 'simple_block', 'gui_hb_bg'),
    'gui_hotbar': ('color_black', 'gui_hotbar', 'gui_hotbar'),
    'gui_hotbar_selected': ('color_cyan', 'gui_hotbar_selected', 'gui_hotbar_selected'),
}

overrides = {
    ('default:fence_acacia_wood', 'bottom'): '_default_fence_acacia_wood_topbottom',
    ('default:fence_acacia_wood', 'inventory'): '_default_fence_acacia_wood',
    ('default:fence_acacia_wood', 'sides'): '_default_fence_acacia_wood_sides',
    ('default:fence_acacia_wood', 'top'): '_default_fence_acacia_wood_topbottom',
    ('default:fence_acacia_wood', 'wield'): '_default_fence_acacia_wood',
    ('default:fence_aspen_wood', 'bottom'): '_default_fence_aspen_wood_topbottom',
    ('default:fence_aspen_wood', 'inventory'): '_default_fence_aspen_wood',
    ('default:fence_aspen_wood', 'sides'): '_default_fence_aspen_wood_sides',
    ('default:fence_aspen_wood', 'top'): '_default_fence_aspen_wood_topbottom',
    ('default:fence_aspen_wood', 'wield'): '_default_fence_aspen_wood',
    ('default:fence_junglewood', 'bottom'): '_default_fence_junglewood_topbottom',
    ('default:fence_junglewood', 'inventory'): '_default_fence_junglewood',
    ('default:fence_junglewood', 'sides'): '_default_fence_junglewood_sides',
    ('default:fence_junglewood', 'top'): '_default_fence_junglewood_topbottom',
    ('default:fence_junglewood', 'wield'): '_default_fence_junglewood',
    ('default:fence_pine_wood', 'bottom'): '_default_fence_pine_wood_topbottom',
    ('default:fence_pine_wood', 'inventory'): '_default_fence_pine_wood',
    ('default:fence_pine_wood', 'sides'): '_default_fence_pine_wood_sides',
    ('default:fence_pine_wood', 'top'): '_default_fence_pine_wood_topbottom',
    ('default:fence_pine_wood', 'wield'): '_default_fence_pine_wood',
    ('default:fence_wood', 'bottom'): '_default_fence_wood_topbottom',
    ('default:fence_wood', 'inventory'): '_default_fence_wood',
    ('default:fence_wood', 'sides'): '_default_fence_wood_sides',
    ('default:fence_wood', 'top'): '_default_fence_wood_topbottom',
    ('default:fence_wood', 'wield'): '_default_fence_wood',
}
