textures = {
    'farming_bread': ('bread', 'bread', 'bread'),
    'farming_cotton': ('cotton', 'simple_block', 'cotton'),
    'farming_cotton_1': ('cotton_plant_1', 'simple_block', 'cotton_1'),
    'farming_cotton_2': ('cotton_plant_1', 'simple_block', 'cotton_2'),
    'farming_cotton_3': ('cotton_plant_1', 'simple_block', 'cotton_3'),
    'farming_cotton_4': ('cotton_plant_1', 'simple_block', 'cotton_4'),
    'farming_cotton_5': ('cotton_plant_1', 'simple_block', 'cotton_5'),
    'farming_cotton_6': ('cotton_plant_1', 'simple_block', 'cotton_6'),
    'farming_cotton_7': ('cotton_plant_2', 'simple_block', 'cotton_7'),
    'farming_cotton_8': (('cotton_plant_2', 'cotton'), 'cotton_8', 'cotton_8'),
    'farming_cotton_seed': ('cotton_seed', 'simple_block', 'seed'),
    'farming_desert_sand_soil': ('desert_sand', 'soil'),
    'farming_desert_sand_soil_wet': ('desert_sand_wet', 'soil'),
    'farming_desert_sand_soil_wet_side': ('desert_sand_wet', 'sand'),
    'farming_flour': ('flour', 'simple_block', 'flour'),
    'farming_soil': ('dirt', 'soil'),
    'farming_soil_wet': ('dirt_wet', 'soil'),
    'farming_soil_wet_side': ('dirt_wet', 'simple_block'),
    'farming_straw': ('wheat_plant_2', 'straw'),
    'farming_tool_bronzehoe': (('bronze', 'wood'), 'hoe', 'hoe'),
    'farming_tool_diamondhoe': (('diamond', 'wood'), 'hoe', 'hoe'),
    'farming_tool_mesehoe': (('mese', 'wood'), 'hoe', 'hoe'),
    'farming_tool_steelhoe': (('steel', 'wood'), 'hoe', 'hoe'),
    'farming_tool_stonehoe': (('stone', 'wood'), 'hoe', 'hoe'),
    'farming_tool_woodhoe': (('wood', 'wood'), 'hoe', 'hoe'),
    'farming_wheat': (('wheat_plant_2', 'wheat'), 'wheat', 'wheat'),
    'farming_wheat_1': ('wheat_plant_1', 'simple_block', 'wheat_1'),
    'farming_wheat_2': ('wheat_plant_1', 'simple_block', 'wheat_2'),
    'farming_wheat_3': ('wheat_plant_1', 'simple_block', 'wheat_3'),
    'farming_wheat_4': ('wheat_plant_1', 'simple_block', 'wheat_4'),
    'farming_wheat_5': ('wheat_plant_1', 'simple_block', 'wheat_5'),
    'farming_wheat_6': ('wheat_plant_1', 'simple_block', 'wheat_6'),
    'farming_wheat_7': ('wheat_plant_2', 'simple_block', 'wheat_7'),
    'farming_wheat_8': (('wheat_plant_2', 'wheat'), 'wheat_8', 'wheat_8'),
    'farming_wheat_seed': ('wheat_seed', 'simple_block', 'seed'),
}
