textures = {
    'gloopores_akalin_block': ('akalin', 'ore_block'),
    'gloopores_akalin_ingot': ('akalin', 'cuboid', 'cuboid'),
    'gloopores_akalin_lump': ('akalin', 'ore_lump', 'ore_lump'),
    'gloopores_alatro_block': ('alatro', 'ore_block'),
    'gloopores_alatro_ingot': ('alatro', 'cuboid', 'cuboid'),
    'gloopores_alatro_lump': ('alatro', 'ore_lump', 'ore_lump'),
    'gloopores_arol_ingot': ('arol', 'cuboid', 'cuboid'),
    'gloopores_arol_lump': ('arol', 'ore_lump', 'ore_lump'),
    'gloopores_kalite_lump': ('kalite', 'ore_lump', 'ore_lump'),
    'gloopores_kalite_torch_animated': (('wood', 'kalite'), 'torch_wall', 'torch_wall'),
    'gloopores_kalite_torch_on_ceiling_animated': (('wood', 'kalite'), 'torch_ceiling', 'torch_ceiling'),
    'gloopores_kalite_torch_on_floor': (('wood', 'kalite'), 'torch_floor', 'torch_floor'),
    'gloopores_kalite_torch_on_floor_animated': 'gloopores_kalite_torch_on_floor',
    'gloopores_mineral_akalin': ('akalin', 'simple_block', 'mineral'),
    'gloopores_mineral_alatro': ('alatro', 'simple_block', 'mineral'),
    'gloopores_mineral_arol': ('arol', 'simple_block', 'mineral'),
    'gloopores_mineral_kalite': ('kalite', 'simple_block', 'mineral'),
    'gloopores_mineral_talinite': ('talinite', 'simple_block', 'mineral'),
    'gloopores_talinite_block': ('talinite', 'ore_block'),
    'gloopores_talinite_ingot': ('talinite', 'cuboid', 'cuboid'),
    'gloopores_talinite_lump': ('talinite', 'ore_lump', 'ore_lump'),
    'gloopores_tool_alatroaxe': (('alatro', 'wood'), 'axe', 'axe'),
    'gloopores_tool_alatropick': (('alatro', 'wood'), 'pick', 'pick'),
    'gloopores_tool_alatroshovel': (('alatro', 'wood'), 'shovel', 'shovel'),
    'gloopores_tool_alatrosword': (('alatro', 'wood'), 'sword', 'sword'),
    'gloopores_tool_arolaxe': (('arol', 'wood'), 'axe', 'axe'),
    'gloopores_tool_arolpick': (('arol', 'wood'), 'pick', 'pick'),
    'gloopores_tool_arolshovel': (('arol', 'wood'), 'shovel', 'shovel'),
    'gloopores_tool_arolsword': (('arol', 'wood'), 'sword', 'sword'),
    'glooptest_gem_amethyst': ('amethyst', 'ore_crystal', 'ore_crystal'),
    'glooptest_gem_emerald': ('emerald', 'ore_crystal', 'ore_crystal'),
    'glooptest_gem_ruby': ('ruby', 'ore_crystal', 'ore_crystal'),
    'glooptest_gem_sapphire': ('sapphire', 'ore_crystal', 'ore_crystal'),
    'glooptest_gem_topaz': ('topaz', 'ore_crystal', 'ore_crystal'),
    'glooptest_mineral_amethyst': ('amethyst', 'simple_block', 'mineral'),
    'glooptest_mineral_emerald': ('emerald', 'simple_block', 'mineral'),
    'glooptest_mineral_ruby': ('ruby', 'simple_block', 'mineral'),
    'glooptest_mineral_sapphire': ('sapphire', 'simple_block', 'mineral'),
    'glooptest_mineral_topaz': ('topaz', 'simple_block', 'mineral'),
    'glooptest_tool_alatrohammer': (('alatro', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_alatrohandsaw': (('alatro', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_arolhammer': (('arol', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_arolhandsaw': (('arol', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_bronzehammer': (('bronze', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_bronzehandsaw': (('bronze', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_diamondhammer': (('diamond', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_diamondhandsaw': (('diamond', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_mesehammer': (('mese', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_mesehandsaw': (('mese', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_steelhammer': (('steel', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_steelhandsaw': (('steel', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_stonehammer': (('stone', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_stonehandsaw': (('stone', 'wood'), 'handsaw', 'handsaw'),
    'glooptest_tool_woodhammer': (('wood', 'wood'), 'hammer', 'hammer'),
    'glooptest_tool_woodhandsaw': (('wood', 'wood'), 'handsaw', 'handsaw'),
}
