textures = {
    'moretrees_apple_tree_leaves': ('apple_tree_leaves', 'simple_block', 'leaves'),
    'moretrees_apple_tree_sapling': (('apple_tree_tree', 'apple_tree_leaves'), 'sapling', 'sapling'),
    'moretrees_apple_tree_trunk': ('apple_tree_tree', 'tree'),
    'moretrees_apple_tree_trunk_top': (('apple_tree_tree', 'apple_tree_wood'), 'tree_top'),
    'moretrees_apple_tree_wood': ('apple_tree_wood', 'wood'),
    'moretrees_beech_leaves': ('beech_leaves', 'simple_block', 'leaves'),
    'moretrees_beech_sapling': (('beech_tree', 'beech_leaves'), 'sapling', 'sapling'),
    'moretrees_beech_trunk': ('beech_tree', 'tree'),
    'moretrees_beech_trunk_top': (('beech_tree', 'beech_wood'), 'tree_top'),
    'moretrees_beech_wood': ('beech_wood', 'wood'),
    'moretrees_birch_leaves': ('birch_leaves', 'simple_block', 'leaves'),
    'moretrees_birch_sapling': (('birch_tree', 'birch_leaves'), 'sapling', 'sapling'),
    'moretrees_birch_trunk': ('birch_tree', 'aspen_tree'),
    'moretrees_birch_trunk_top': (('birch_tree', 'birch_wood'), 'aspen_tree_top'),
    'moretrees_birch_wood': ('birch_wood', 'wood'),
    'moretrees_cedar_leaves': ('cedar_leaves', 'simple_block', 'pine_needles'),
    'moretrees_cedar_sapling': (('cedar_tree', 'cedar_leaves'), 'sapling', 'sapling'),
    'moretrees_cedar_trunk': ('cedar_tree', 'tree'),
    'moretrees_cedar_trunk_top': (('cedar_tree', 'cedar_wood'), 'tree_top'),
    'moretrees_cedar_wood': ('cedar_wood', 'wood'),
}
