textures = {
    "moreores_copper_rail": (("wood", "copper"), "rail", "rail"),
    "moreores_copper_rail_crossing": (("wood", "copper"), "rail_crossing", "rail_crossing"),
    "moreores_copper_rail_curved": (("wood", "copper"), "rail_curved", "rail_curved"),
    "moreores_copper_rail_t_junction": (("wood", "copper"), "rail_t_junction", "rail_t_junction"),
    "moreores_mineral_mithril": ("mithril", "simple_block", "mineral"),
    "moreores_mineral_silver": ("silver", "simple_block", "mineral"),
    "moreores_mineral_tin": ("tin", "simple_block", "mineral"),
    "moreores_mithril_block": ("mithril", "ore_block"),
    "moreores_mithril_ingot": ("mithril", "cuboid", "cuboid"),
    "moreores_mithril_lump": ("mithril", "ore_lump", "ore_lump"),
    "moreores_silver_block": ("silver", "ore_block"),
    "moreores_silver_ingot": ("silver", "cuboid", "cuboid"),
    "moreores_silver_lump": ("silver", "ore_lump", "ore_lump"),
    "moreores_tin_block": ("tin", "ore_block"),
    "moreores_tin_ingot": ("tin", "cuboid", "cuboid"),
    "moreores_tin_lump": ("tin", "ore_lump", "ore_lump"),
    "moreores_tool_mithrilaxe": (("mithril", "wood"), "axe", "axe"),
    "moreores_tool_mithrilhoe": (("mithril", "wood"), "hoe", "hoe"),
    "moreores_tool_mithrilpick": (("mithril", "wood"), "pick", "pick"),
    "moreores_tool_mithrilshovel": (("mithril", "wood"), "shovel", "shovel"),
    "moreores_tool_mithrilsword": (("mithril", "wood"), "sword", "sword"),
    "moreores_tool_silveraxe": (("silver", "wood"), "axe", "axe"),
    "moreores_tool_silverhoe": (("silver", "wood"), "hoe", "hoe"),
    "moreores_tool_silverpick": (("silver", "wood"), "pick", "pick"),
    "moreores_tool_silvershovel": (("silver", "wood"), "shovel", "shovel"),
    "moreores_tool_silversword": (("silver", "wood"), "sword", "sword"),
}
