textures = {
    "moreblocks_cactus_brick": ("cactus_1", "brick"),
    "moreblocks_cactus_checker": ("cactus_1", "simple_block", "checkerboard_4x4"),
    "moreblocks_clean_glass": ("glass", "simple_block", "clean_glass"),
    "moreblocks_clean_glass_detail": ("glass", "simple_block", "clean_glass_detail"),
    "moreblocks_coal_checker": ("coal", "simple_block", "checkerboard_4x4"),
    "moreblocks_coal_glass": ("coal", "simple_block", "glass"),
    "moreblocks_coal_glass_detail": ("coal", "simple_block", "glass_detail"),
    "moreblocks_glow_glass": ("glow_glass", "simple_block", "glass"),
    "moreblocks_glow_glass_detail": ("glow_glass", "simple_block", "glass_detail"),
    "moreblocks_iron_checker": ("steel", "simple_block", "checkerboard_4x4"),
    "moreblocks_iron_glass": ("steel", "simple_block", "glass"),
    "moreblocks_iron_glass_detail": ("steel", "simple_block", "glass_detail"),
    "moreblocks_super_glow_glass": ("super_glow_glass", "simple_block", "glass"),
    "moreblocks_super_glow_glass_detail": ("super_glow_glass", "simple_block", "glass_detail"),
}
