textures = {
    'technic_brass_block': ('brass', 'ore_block'),
    'technic_brass_ingot': ('brass', 'cuboid', 'cuboid'),
    'technic_carbon_steel_block': ('carbon_steel', 'ore_block'),
    'technic_carbon_steel_ingot': ('carbon_steel', 'cuboid', 'cuboid'),
    'technic_cast_iron_block': ('cast_iron', 'ore_block'),
    'technic_cast_iron_ingot': ('cast_iron', 'cuboid', 'cuboid'),
    'technic_chromium_block': ('chromium', 'ore_block'),
    'technic_chromium_ingot': ('chromium', 'cuboid', 'cuboid'),
    'technic_chromium_lump': ('chromium', 'ore_lump', 'ore_lump'),
    'technic_granite': (('granite_1', 'granite_2'), 'granite'),
    'technic_lead_block': ('lead', 'ore_block'),
    'technic_lead_ingot': ('lead', 'cuboid', 'cuboid'),
    'technic_lead_lump': ('lead', 'ore_lump', 'ore_lump'),
    'technic_marble': ('marble', 'marble'),
    'technic_marble_bricks': ('marble', 'brick'),
    'technic_mineral_chromium': ('chromium', 'simple_block', 'mineral'),
    'technic_mineral_lead': ('lead', 'simple_block', 'mineral'),
    'technic_mineral_sulfur': ('sulfur', 'simple_block', 'mineral'),
    'technic_mineral_uranium': ('uranium', 'simple_block', 'mineral'),
    'technic_mineral_zinc': ('zinc', 'simple_block', 'mineral'),
    'technic_rubber': ('rubber', 'circle', 'circle'),
    'technic_rubber_leaves': 'moretrees_rubber_tree_leaves',
    'technic_rubber_sapling': 'moretrees_rubber_tree_sapling',
    'technic_rubber_tree_empty': 'moretrees_rubber_tree_trunk_empty',
    'technic_rubber_tree_full': 'moretrees_rubber_tree_trunk',
    'technic_stainless_steel_block': ('stainless_steel', 'ore_block'),
    'technic_stainless_steel_ingot': ('stainless_steel', 'cuboid', 'cuboid'),
    'technic_sulfur_lump': ('sulfur', 'ore_lump', 'ore_lump'),
    'technic_uranium_block': ('uranium', 'ore_block'),
    'technic_uranium_ingot': ('uranium', 'cuboid', 'cuboid'),
    'technic_uranium_lump': ('uranium', 'ore_lump', 'ore_lump'),
    'technic_wrought_iron_block': 'default_steel_block',
    'technic_wrought_iron_ingot': 'default_steel_ingot',
    'technic_zinc_block': ('zinc', 'ore_block'),
    'technic_zinc_ingot': ('zinc', 'cuboid', 'cuboid'),
    'technic_zinc_lump': ('zinc', 'ore_lump', 'ore_lump'),
}

overrides_noprefix = {
    ('moretrees:rubber_tree_trunk', 'bottom'): 'moretrees_rubber_tree_trunk_top',
    ('moretrees:rubber_tree_trunk', 'top'): 'moretrees_rubber_tree_trunk_top',
}
