textures = {
    "_technic_locked_chest_overlay_black": ("color_black", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_blue": ("color_blue", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_brown": ("color_brown", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_cyan": ("color_cyan", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_dark_green": ("color_dark_green", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_dark_grey": ("color_dark_gray", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_green": ("color_green", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_grey": ("color_gray", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_magenta": ("color_magenta", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_orange": ("color_orange", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_pink": ("color_light_red", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_red": ("color_red", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_violet": ("color_violet", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_white": ("color_white", "chest_lock_overlay", "chest_lock_overlay"),
    "_technic_locked_chest_overlay_yellow": ("color_yellow", "chest_lock_overlay", "chest_lock_overlay"),
    "technic_chest_form_bg": "gui_formbg",
    "technic_chest_overlay_black": ("color_black", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_blue": ("color_blue", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_brown": ("color_brown", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_cyan": ("color_cyan", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_dark_green": ("color_dark_green", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_dark_grey": ("color_dark_gray", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_green": ("color_green", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_grey": ("color_gray", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_magenta": ("color_magenta", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_orange": ("color_orange", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_pink": ("color_light_red", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_red": ("color_red", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_violet": ("color_violet", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_white": ("color_white", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_chest_overlay_yellow": ("color_yellow", "technic_chest_overlay_color", "technic_chest_overlay_color"),
    "technic_colorbutton0": ("color_black", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton1": ("color_blue", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton10": ("color_light_red", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton11": ("color_red", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton12": ("color_violet", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton13": ("color_white", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton14": ("color_yellow", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton2": ("color_brown", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton3": ("color_cyan", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton4": ("color_dark_green", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton5": ("color_dark_gray", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton6": ("color_green", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton7": ("color_gray", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton8": ("color_magenta", "simple_block", "technic_chest_colorbutton"),
    "technic_colorbutton9": ("color_orange", "simple_block", "technic_chest_colorbutton"),
    "technic_copper_chest_front": (("copper", "copper"), "chest_front"),
    "technic_copper_chest_inventory": (
        "listcolors_slot_bg_normal",
        "technic_copper_chest_inventory",
        "technic_copper_chest_inventory",
    ),
    "technic_copper_chest_lock_overlay": ("copper", "chest_lock_overlay", "chest_lock_overlay"),
    "technic_copper_chest_side": ("copper", "chest_side"),
    "technic_copper_chest_top": ("copper", "chest_top"),
    "technic_gold_chest_front": (("gold", "gold"), "chest_front"),
    "technic_gold_chest_inventory": (
        "listcolors_slot_bg_normal",
        "technic_gold_chest_inventory",
        "technic_gold_chest_inventory",
    ),
    "technic_gold_chest_lock_overlay": ("gold", "chest_lock_overlay", "chest_lock_overlay"),
    "technic_gold_chest_side": ("gold", "chest_side"),
    "technic_gold_chest_top": ("gold", "chest_top"),
    "technic_iron_chest_front": (("steel", "steel"), "chest_front"),
    "technic_iron_chest_inventory": (
        "listcolors_slot_bg_normal",
        "technic_iron_chest_inventory",
        "technic_iron_chest_inventory",
    ),
    "technic_iron_chest_lock_overlay": ("steel", "chest_lock_overlay", "chest_lock_overlay"),
    "technic_iron_chest_side": ("steel", "chest_side"),
    "technic_iron_chest_top": ("steel", "chest_top"),
    "technic_main_inventory": "ui_main_inventory",
    "technic_mithril_chest_front": (("mithril", "mithril"), "chest_front"),
    "technic_mithril_chest_inventory": (
        "listcolors_slot_bg_normal",
        "technic_mithril_chest_inventory",
        "technic_mithril_chest_inventory",
    ),
    "technic_mithril_chest_lock_overlay": ("mithril", "chest_lock_overlay", "chest_lock_overlay"),
    "technic_mithril_chest_side": ("mithril", "chest_side"),
    "technic_mithril_chest_top": ("mithril", "chest_top"),
    "technic_silver_chest_front": (("silver", "silver"), "chest_front"),
    "technic_silver_chest_inventory": (
        "listcolors_slot_bg_normal",
        "technic_silver_chest_inventory",
        "technic_silver_chest_inventory",
    ),
    "technic_silver_chest_lock_overlay": ("silver", "chest_lock_overlay", "chest_lock_overlay"),
    "technic_silver_chest_side": ("silver", "chest_side"),
    "technic_silver_chest_top": ("silver", "chest_top"),
    "technic_wooden_chest_inventory": (
        "listcolors_slot_bg_normal",
        "technic_wooden_chest_inventory",
        "technic_wooden_chest_inventory",
    ),
}

overrides = {
    ("technic:gold_locked_chest_black", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_black"),
    ("technic:gold_locked_chest_blue", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_blue"),
    ("technic:gold_locked_chest_brown", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_brown"),
    ("technic:gold_locked_chest_cyan", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_cyan"),
    ("technic:gold_locked_chest_dark_green", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_dark_green"),
    ("technic:gold_locked_chest_dark_grey", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_dark_grey"),
    ("technic:gold_locked_chest_green", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_green"),
    ("technic:gold_locked_chest_grey", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_grey"),
    ("technic:gold_locked_chest_magenta", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_magenta"),
    ("technic:gold_locked_chest_orange", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_orange"),
    ("technic:gold_locked_chest_pink", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_pink"),
    ("technic:gold_locked_chest_red", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_red"),
    ("technic:gold_locked_chest_violet", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_violet"),
    ("technic:gold_locked_chest_white", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_white"),
    ("technic:gold_locked_chest_yellow", "front"): ("technic_gold_chest_front", "_technic_locked_chest_overlay_yellow"),
}
